name: api_com

description: Package for easy communication with PHP APIs.
repository: https://github.com/CreevekCZ/api_com
version: 0.1.3

environment:
  sdk: '>=3.0.1 <4.0.0'
  

dependencies: 
  collection: ^1.15.0
  connectivity_plus: ^4.0.1
  http: ^0.13.5
  palestine_console: ^0.0.10

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.1