name: api_com

description: Package for easy communication with PHP APIs. 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  http: ^0.13.3
  connectivity_plus: ^1.2.0
  palestine_console: ^0.0.10
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^1.0.0