name: api_com

description: Package for easy communication with PHP APIs.
repository: https://github.com/CreevekCZ/api_com
version: 0.1.2

environment:
  sdk: '>=2.17.0 <3.0.0'
  

dependencies: 
  connectivity_plus: ^1.2.0
  http: ^0.13.3
  palestine_console: ^0.0.10
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.1